# Generated by Django 5.2.1 on 2025-05-23 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='予約者名')),
                ('date', models.DateField(verbose_name='予約日')),
                ('time_slot', models.CharField(max_length=5, verbose_name='予約時間帯')),
                ('booked_at', models.DateTimeField(auto_now_add=True, verbose_name='予約日時')),
            ],
            options={
                'verbose_name': '予約',
                'verbose_name_plural': '予約一覧',
                'unique_together': {('date', 'time_slot')},
            },
        ),
    ]
