# Generated by Django 5.2.1 on 2025-08-28 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='タイトル')),
                ('date', models.DateField(verbose_name='日付')),
            ],
            options={
                'verbose_name': '全体スケジュール',
                'verbose_name_plural': '全体スケジュール一覧',
            },
        ),
    ]