# Generated by Django 5.2.4 on 2025-08-28 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0002_schedule'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='schedule',
            options={'ordering': ['date'], 'verbose_name': 'スケジュール', 'verbose_name_plural': 'スケジュール一覧'},
        ),
        migrations.AddField(
            model_name='schedule',
            name='description',
            field=models.TextField(blank=True, verbose_name='説明'),
        ),
    ]
